[package]
edition = "2021"
name = "yew-debug"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-agent = "0.2.0"
